#pragma once
#define PADDLE_DEFAULT_VELOCITY .1f

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define PADDLE_DEFAULT_X (WINDOW_WIDTH/2)
#define PADDLE_DEFAULT_Y 500

#define PADDLE_WIDTH 200
#define PADDLE_HEIGHT 20

#define BALL_DEFAULT_X 100
#define BALL_DEFAULT_Y 100

#define BALL_RADIUS 15
#define BALL_DEFAULT_VELOCITY_X 300
#define BALL_DEFAULT_VELOCITY_Y 300

#define PADDING 0
#define DEFAULT_VELOCITY_CLAMP .1f

#define MAX_ENTITIES 700








