#pragma once
#define PADDLE_DEFAULT_VELOCITY .1f

#define WINDOW_WIDTH 600
#define WINDOW_HEIGHT 800

#define PADDLE_DEFAULT_X (WINDOW_WIDTH/2)
#define PADDLE_DEFAULT_Y 500

#define PADDLE_WIDTH 200
#define PADDLE_HEIGHT 20

#define BALL_DEFAULT_X (WINDOW_WIDTH/2)
#define BALL_DEFAULT_Y (WINDOW_HEIGHT/2)

#define BALL_RADIUS 3
#define BALL_DEFAULT_VELOCITY 3

#define PADDING 3
#define DEFAULT_VELOCITY_CLAMP .1f







